version: "2"
run:
  timeout: 13m
linters:
  default: none
  # TODO: we should be enabling far more linters ...
  enable:
    - govet
    - unused
    - misspell
    - ineffassign
    - staticcheck
  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 50
    govet:
      enable:
        - nilness
    staticcheck:
      checks:
      - all
      # disable: could remove embedded field "field" from selector
      # explicit selectors can be clearer
      - '-QF1008'
      # TODO: re-enable. We have a lot of packages without comments and the
      # diff to upgrade go is already huge
      - '-ST1000'
      # We have a lot of legacy capitalized error strings
      - '-ST1005'
  exclusions:
    paths:
      - .git
      - .tool
      - vendor
      - verify
    rules:
      - linters:
        - golint
        text: ".*should not use dot dot imports"
      - linters:
        - staticcheck
        text: "SA1019: fakectrlruntimeclient.NewFakeClient is deprecated"
      - linters:
        - staticcheck
        # TODO: Is this really supposed to be deprecated? Ref https://github.com/kubernetes/test-infra/issues/14875
        text: "SA1019: t.*.TrustedOrg is deprecated: TrustedOrg functionality is deprecated and will be removed in January 2020"
