run:
  deadline: 13m

linters-settings:
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 50
  govet:
    enable:
      - nilness

linters:
  # TODO: we should be enabling far more linters ...
  enable:
  - govet
  - unused
  - misspell
  - ineffassign
  - staticcheck
  - gosimple
  disable-all: true

issues:
  skip-dirs:
  - .git
  - .tool
  - vendor
  - verify
  exclude-rules:
  - linters:
    - golint
    text: ".*should not use dot dot imports"
  - linters:
    - staticcheck
    text: "SA1019: fakectrlruntimeclient.NewFakeClient is deprecated"
  - linters:
    - staticcheck
    # TODO: Is this really supposed to be deprecated? Ref https://github.com/kubernetes/test-infra/issues/14875
    text: "SA1019: t.*.TrustedOrg is deprecated: TrustedOrg functionality is deprecated and will be removed in January 2020"
