postsubmits:
  kubernetes/org:
  - name: post-org-peribolos
    cluster: test-infra-trusted
    decorate: true
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel
        command:
        - bazel
        args:
        - run
        - //admin:update
        - --
        - --github-token-path=/etc/github-token/oauth
        - --confirm
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
      volumes:
      - name: github
        secret:
          secretName: oauth-token
  kubernetes/test-infra:
  - name: post-test-infra-push-prow
    cluster: test-infra-trusted
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20181002-996397d
        command:
        - prow/bump.sh
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /creds/service-account.json
        volumeMounts:
        - name: creds
          mountPath: /creds
      volumes:
      - name: creds
        secret:
          secretName: pusher-service-account

periodics:
- interval: 24h
  name: ci-org-peribolos
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: org
    base_ref: master
  spec:
    containers:
    - image: launcher.gcr.io/google/bazel
      command:
      - bazel
      args:
      - run
      - //admin:update
      - --
      - --github-token-path=/etc/github-token/oauth
      - --confirm
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
    volumes:
    - name: github
      secret:
        secretName: oauth-token
- cron: "54 * * * *"  # Every hour at 54 minutes past the hour 
  name: ci-branchprotector
  cluster: test-infra-trusted
  decorate: true
  spec: 
    containers:
    - name: branchprotector
      image: gcr.io/k8s-prow/branchprotector:v20181019-08e9d55c9
      args:
      - --config-path=/etc/config/config.yaml
      - --job-config-path=/etc/job-config
      - --github-token-path=/etc/github/oauth
      - --confirm
      - --github-endpoint=http://ghproxy
      - --github-endpoint=https://api.github.com
      volumeMounts:
      - name: oauth
        mountPath: /etc/github
        readOnly: true
      - name: config
        mountPath: /etc/config
        readOnly: true
      - name: job-config
        mountPath: /etc/job-config
        readOnly: true
    volumes:
    - name: oauth
      secret:
        secretName: oauth-token
    - name: config
      configMap:
        name: config
    - name: job-config
      configMap:
        name: job-config
